pipeline_version: 1.0.0 #Optional - Version of IaC module to be used - If not specified, the latest release of IaC will be used.
topic:
  name: "<Topic Name with naming convention>" #Required - Naming convention - DataCenter.Environment.OwningMalAcronym.EnterpriseDesignatorTaxonomy.CapabilityTaxonomy.Format.MessagePattern
  alias_name: "<Friendly name>" #Optional - This is would be the name of the tf state file. If not provided, would be derieved from the filename. 
  description: "<Description about topic>" #Optional - Just a metadata
  mal_acronym: "<MAL Acronym>" #Required - Just a metadata
  srb_review_number: "<SRB Review Ticket>" #Required - Just a metadata
  
  # Following are basic configurations supported
  partitions: 1 #Optional
  retention: 1d #Optional #Supported units: s (seconds), m(minutes), h(hours), d(days)
  cleanup_policy: "delete" #Optional #Supported values: delete, compact
  
  # Following are advanced configurations supported
  config:       #Optional - The following configs are supported and are optional
    # Following are only supported in the config section - As per 2.25 version of Confluent provider
    delete.retention.ms: 86400000
    max.message.bytes: 1048576
    max.compaction.lag.ms: 86400000
    message.timestamp.difference.max.ms: 86400000
    message.timestamp.before.max.ms: 86400000
    message.timestamp.after.max.ms:   86400000
    message.timestamp.type: "CreateTime"
    min.compaction.lag.ms: 0 
    min.insync.replicas: 1 
    retention.bytes: 1073741824
    retention.ms: 604800000
    segment.bytes:  1073741824
    segment.ms: 604800000
    confluent.key.schema.validation: "false"
    confluent.value.schema.validation: "false"
    confluent.key.subject.name.strategy: "TopicNameStrategy"
    confluent.value.subject.name.strategy:  "TopicNameStrategy"